### ISSUE TITLE
Rewrite using sublime-syntax format

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-syntax-highlight#108]
The current highlight is adapted from the ST2 HTML syntax, originally written in the `tmlanguage` format and compiled from YAML.

ST3 now supports its own `sublime-syntax` format and ideally this package should be rewritten based on the [new HTML syntax in ST3](https://github.com/sublimehq/Packages/blob/master/HTML/HTML.sublime-syntax).

This is an open call if anyone wants to take a stab at it - I have included a [samples directory](https://github.com/vuejs/vue-syntax-highlight/tree/master/samples) to verify basic highlighting behavior. Documentation for ST3 syntax definitions are [here](https://www.sublimetext.com/docs/3/syntax.html).

**Comment by skyronic** [comment]
I would very much like to contribute to this. Will work on it right now and report back if I could make progress.

**Comment by eddyerburgh** [comment]
Can we also add support for <test> blocks highlighted as JavaScript by default and <docs> blocks highlighted as markdown by default?

**Comment by Thom1729** [comment]
The current core HTML syntax definition uses the new `embed`/`escape` idiom implemented in dev build 3153. It would probably be best to use the same method here. It's not in the syntax definition docs yet, but partial documentation is available [here](https://forum.sublimetext.com/t/dev-build-3153/33014/8).

Also, I don't know much about Vue in general or this syntax in particular, but if this syntax definition is basically HTML extended with additional features, then it might be possible to use my [YAML Macros](https://github.com/Thom1729/YAML-Macros) package to directly extend the core HTML syntax in a forward-compatible manner. That way, the Vue syntax could avoid reimplementing HTML itself. An example (implementing JSX by extending the core JavaScript package) can be seen [here](https://github.com/Thom1729/YAML-Macros/blob/master/examples/jsx/jsx.sublime-syntax.yaml-macros).

**Comment by skyronic** [comment]
@Thom1729 I've made a little bit of progress. I discovered `embed`/`escape` while looking at the HTML language but found that it doesn't support `with_prototype` or rather threw an error while using it directly.

In fact, I tried various methods which worked with less success and am taking this direction right now which seems to be working

```yaml
%YAML 1.2
---
name: Vue Component
file_extensions: [vue]
scope: source.vue

contexts:
  main:
    - match: '<template>'
      scope: text.html.basic
      push:
        - meta_scope: text.html.basic
        - match: '</template>'
          pop: true
        - include: scope:text.html.basic
        - match: '{{'
          push:
          - meta_scope: source.js
          - match: '}}'
            pop: true
          - include: scope:source.js
    - match: '<style>'
      push:
        - meta_scope: source.css
        - match: '</style>'
          pop: true
        - include: scope:source.css

    - match: '<script>'
      push:
        - meta_scope: source.js
        - match: '</script>'
          pop: true
        - include: scope:source.js
```

I noticed that we can `include: scope:source.js` and I found this in the RestructuredText language file. If you're familiar with this, would appreciate some feedback on whether this direction is ok.
